### ISSUE TITLE
Peer Review 

### ISSUE THREAD

**Issue by rokmesojedec** [nhillsbos/e28#1]
Hi Nick, 

I uploaded the peer review for your project. I hope it's helpful for you and I hope I wasn't too critical.

[https://github.com/rokmesojedec/e28/blob/master/peer-review/peer-review.md](https://github.com/rokmesojedec/e28/blob/master/peer-review/peer-review.md)

Best, 
Rok

**Comment by nhillsbos** [comment]
Thank you. I looked at it briefly this morning. It seems like you had fun! Well, it looks useful. So I will definitely take your review into consideration when finishing my final project.

**Comment by rokmesojedec** [comment]
It certainly was interesting and I learned a thing or two about Daoism :)
